/*
 * Copyright 2024 The Hafnium Authors.
 *
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/BSD-3-Clause.
 */

#pragma once

enum manifest_return_code {
	MANIFEST_SUCCESS = 0,
	MANIFEST_ERROR_FILE_SIZE,
	MANIFEST_ERROR_NO_ROOT_NODE,
	MANIFEST_ERROR_NO_HYPERVISOR_FDT_NODE,
	MANIFEST_ERROR_NOT_COMPATIBLE,
	MANIFEST_ERROR_RESERVED_VM_ID,
	MANIFEST_ERROR_NO_PRIMARY_VM,
	MANIFEST_ERROR_TOO_MANY_VMS,
	MANIFEST_ERROR_PROPERTY_NOT_FOUND,
	MANIFEST_ERROR_MALFORMED_STRING,
	MANIFEST_ERROR_STRING_TOO_LONG,
	MANIFEST_ERROR_MALFORMED_INTEGER,
	MANIFEST_ERROR_INTEGER_OVERFLOW,
	MANIFEST_ERROR_MALFORMED_INTEGER_LIST,
	MANIFEST_ERROR_MALFORMED_BOOLEAN,
	MANIFEST_ERROR_MEMORY_REGION_NODE_EMPTY,
	MANIFEST_ERROR_DEVICE_REGION_NODE_EMPTY,
	MANIFEST_ERROR_RXTX_SIZE_MISMATCH,
	MANIFEST_ERROR_MEM_REGION_EMPTY,
	MANIFEST_ERROR_MEM_REGION_UNALIGNED,
	MANIFEST_ERROR_BASE_ADDRESS_AND_RELATIVE_ADDRESS,
	MANIFEST_ERROR_MEM_REGION_OVERLAP,
	MANIFEST_ERROR_MEMORY_MISSING,
	MANIFEST_ERROR_MEM_REGION_INVALID,
	MANIFEST_ERROR_DEVICE_MEM_REGION_INVALID,
	MANIFEST_ERROR_INVALID_MEM_PERM,
	MANIFEST_ERROR_INTERRUPT_ID_REPEATED,
	MANIFEST_ERROR_ILLEGAL_NS_INT_ACTION,
	MANIFEST_ERROR_ILLEGAL_SRI_POLICY,
	MANIFEST_ERROR_SRI_POLICY_NOT_SUPPORTED,
	MANIFEST_ERROR_INTERRUPT_ID_NOT_IN_LIST,
	MANIFEST_ERROR_ILLEGAL_OTHER_S_INT_ACTION,
	MANIFEST_ERROR_INVALID_BOOT_ORDER,
	MANIFEST_ERROR_UNMATCHED_MESSAGING_METHODS,
	MANIFEST_ERROR_INVALID_MESSAGING_METHOD,
	MANIFEST_ERROR_UUID_ALL_ZEROS,
	MANIFEST_ERROR_TOO_MANY_UUIDS,
	MANIFEST_ERROR_MALFORMED_UUID,
	MANIFEST_ERROR_DUPLICATE_UUID,
	MANIFEST_ERROR_MISSING_SMMU_ID,
	MANIFEST_ERROR_MISMATCH_DMA_ACCESS_PERMISSIONS,
	MANIFEST_ERROR_STREAM_IDS_OVERFLOW,
	MANIFEST_ERROR_DMA_ACCESS_PERMISSIONS_OVERFLOW,
	MANIFEST_ERROR_DMA_DEVICE_OVERFLOW,
	MANIFEST_ERROR_VM_AVAILABILITY_MESSAGE_INVALID,
	MANIFEST_ERROR_ILLEGAL_LIFECYCLE_SUPPORT,
	MANIFEST_ERROR_ILLEGAL_ABORT_ACTION,
	MANIFEST_ERROR_NO_SERVICES,
};
